@php($outcome = $this->outcome())
<x-filament-panels::page>
<style>
.feol-status{max-width:480px;margin:28px auto;text-align:center}.feol-scene{position:relative;width:240px;height:220px;margin:auto}.feol-glow{position:absolute;width:165px;height:165px;left:50%;top:48%;transform:translate(-50%,-50%);border-radius:50%;background:#eff6ff;animation:fg 2.2s ease-in-out infinite}.feol-shadow{position:absolute;width:112px;height:18px;left:50%;bottom:21px;transform:translateX(-50%);border-radius:50%;background:#0f172214;filter:blur(7px)}.feol-paper{position:absolute;width:116px;height:148px;left:62px;top:25px;border-radius:14px;border:2px solid #dbe4f0;background:#f1f5f9;transform:rotate(-10deg)}.feol-doc{position:absolute;width:124px;height:156px;left:58px;top:17px;background:#fff;border:2px solid #cbd5e1;border-radius:15px;box-shadow:0 24px 48px #0f17221a;overflow:hidden;animation:ff 2.8s ease-in-out infinite}.feol-doc:before{content:'';position:absolute;left:22px;top:33px;width:82px;height:5px;border-radius:5px;background:#bfdbfe;box-shadow:0 16px #dbeafe,0 32px #dbeafe,0 48px #dbeafe}.feol-scan{position:absolute;left:0;width:100%;height:45px;background:linear-gradient(transparent,#3b82f62e,transparent);animation:fs 2.4s ease-in-out infinite}.feol-badge{position:absolute;right:10px;bottom:8px;width:43px;height:43px;display:grid;place-items:center;border-radius:50%;background:#fff;border:1px solid #dbeafe;color:#3b82f6;font-weight:900;box-shadow:0 8px 18px #2563eb29}.feol-result{display:grid;position:absolute;z-index:4;left:50%;top:52%;transform:translate(-50%,-50%);width:76px;height:76px;place-items:center;border-radius:50%;background:#fff;border:2px solid;font-size:50px;font-weight:800}.feol-title{font-size:22px;font-weight:750;color:#334155}.feol-desc{max-width:370px;margin:10px auto;color:#64748b;line-height:1.6}.feol-progress{width:180px;height:4px;margin:20px auto;border-radius:10px;background:#e8eef7;overflow:hidden}.feol-progress:after{content:'';display:block;width:38%;height:100%;background:#3b82f6;animation:fp 2.2s infinite}.feol-status.success .feol-glow{background:#ecfdf5}.feol-status.success .feol-doc{border-color:#86efac}.feol-status.success .feol-result{color:#16a34a;border-color:#86efac}.feol-status.failed .feol-glow{background:#fff7ed}.feol-status.failed .feol-doc{border-color:#fdba74;animation:shake .65s 1}.feol-status.failed .feol-result{color:#f97316;border-color:#fdba74}@keyframes ff{50%{transform:translateY(-6px)}}@keyframes fs{0%{transform:translateY(-50px);opacity:0}15%,75%{opacity:1}100%{transform:translateY(145px);opacity:0}}@keyframes fp{from{transform:translateX(-150%)}to{transform:translateX(400%)}}@keyframes fg{50%{transform:translate(-50%,-50%) scale(1.06)}}@keyframes shake{20%{transform:translateX(-6px)}40%{transform:translateX(6px)}60%{transform:translateX(-4px)}}
</style>
<div class="feol-status {{ $outcome }}" @if($outcome === 'processing') wire:poll.2s="refreshResult" @endif>
 <div class="feol-scene"><div class="feol-glow"></div><div class="feol-shadow"></div><div class="feol-paper"></div><div class="feol-doc"><div class="feol-scan"></div><div class="feol-badge">…</div></div>@if($outcome === 'eligible')<div class="feol-result">✓</div>@elseif($outcome === 'failed')<div class="feol-result">☹</div>@endif</div>
 @if($outcome === 'eligible')
  <div class="feol-title">Chúc mừng! Hồ sơ Khách hàng thoả mãn điều kiện đăng ký hồ sơ vay.</div><p class="feol-desc">Mã hồ sơ: {{ $this->record->application_code }} · ID đối tác: {{ $this->record->feolIntegration?->partner_lead_id ?: '-' }} · Trạng thái: Eligible</p><x-filament::button icon="heroicon-o-clipboard-document" x-on:click="navigator.clipboard.writeText(@js($this->record->feolIntegration?->deeplink_url)); new FilamentNotification().title('Đã sao chép Deeplink').success().send()">Copy Deeplink</x-filament::button>
 @elseif($outcome === 'failed')
  <div class="feol-title">Rất tiếc hồ sơ của Khách hàng không thoả điều kiện.</div><p class="feol-desc">Mã hồ sơ: {{ $this->record->application_code }} · ID đối tác: {{ $this->record->feolIntegration?->partner_lead_id ?: '-' }}</p>
 @else
  <div class="feol-title">Đang xử lý hồ sơ</div><p class="feol-desc">Hệ thống đang kiểm tra thông tin của Khách hàng...</p><div class="feol-progress"></div>
 @endif
</div>
</x-filament-panels::page>
