<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Đang kiểm tra hồ sơ</title>
<style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:#f4f7fb;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033}.card{width:min(100%,560px);padding:42px 30px;text-align:center;background:#fff;border:1px solid #dfe6f0;border-radius:20px;box-shadow:0 18px 50px #20345114}.loader{font-weight:700;font-family:monospace;font-size:30px;display:inline-grid;color:#175cd3;margin:8px auto 24px}.loader:before,.loader:after{content:"Loading...";grid-area:1/1;line-height:1em;-webkit-mask:linear-gradient(90deg,#000 50%,#0000 0) 0 50%/2ch 100%;-webkit-mask-position:calc(var(--s,0)*1ch) 50%;animation:l30 2s infinite}.loader:after{--s:-1}@keyframes l30{33%{transform:translateY(calc(var(--s,1)*50%));-webkit-mask-position:calc(var(--s,0)*1ch) 50%}66%{transform:translateY(calc(var(--s,1)*50%));-webkit-mask-position:calc(var(--s,0)*1ch + 1ch) 50%}100%{transform:translateY(calc(var(--s,1)*0%));-webkit-mask-position:calc(var(--s,0)*1ch + 1ch) 50%}}h1{font-size:25px;margin:0 0 10px}p{color:#66758b;line-height:1.6;margin:0}.status{display:inline-flex;align-items:center;justify-content:center;min-height:34px;margin-top:20px;padding:7px 14px;border-radius:999px;background:#eef4ff;color:#175cd3;font-size:14px;font-weight:700}.status[data-state="completed"]{background:#fff4e5;color:#a15c00}.status[data-state="error"]{background:#fff0f0;color:#b42318}.hint{margin-top:14px;font-size:13px;color:#8995a8}
</style></head><body>
<main class="card"><div class="loader" id="loader" aria-label="Đang tải"></div><h1 id="title">Đang kiểm tra điều kiện</h1><p id="message">Hồ sơ đã được lưu. Hệ thống đang nhận kết quả từ FEOL.</p><div class="status" id="status" data-state="waiting">Vui lòng chờ 1–2 giây</div><p class="hint" id="hint">Không đóng trang này. Nếu đủ điều kiện, hệ thống sẽ tự chuyển bạn đến app FEOL bằng Deeplink.</p></main>
<script>
(()=>{const url=@json($statusUrl),message=document.getElementById('message'),status=document.getElementById('status'),title=document.getElementById('title'),loader=document.getElementById('loader'),hint=document.getElementById('hint');let running=false;const check=async()=>{if(running)return;running=true;try{const response=await fetch(url,{headers:{Accept:'application/json'},cache:'no-store'});if(!response.ok)throw new Error('status_http_'+response.status);const result=await response.json();message.textContent=result.message||'Đang kiểm tra điều kiện hồ sơ...';status.dataset.state=result.state||'waiting';status.textContent=result.status_label||(result.state==='waiting'?'Đang kiểm tra':'Đã có kết quả');if(result.state==='eligible'&&result.redirect_url){title.textContent='Bạn đủ điều kiện';status.textContent='Đang chuyển đến app FEOL';hint.textContent='Chuyển bằng Deeplink đối tác trả về.';window.setTimeout(()=>window.location.replace(result.redirect_url),450);return}if(result.state==='completed'){loader.hidden=true;title.textContent='Rất tiếc bạn chưa đủ điều kiện';status.textContent='Chưa đủ điều kiện';hint.textContent='Quý khách có thể đóng trang này.';return}}catch(error){status.dataset.state='waiting';status.textContent='Đang kiểm tra';message.textContent='Đang kiểm tra điều kiện hồ sơ với FEOL...'}finally{running=false}window.setTimeout(check,1000)};check()})();
</script></body></html>
